version: "3.8"

services:
  app:
    build: .
    container_name: historia-clinica-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: node src/index.js
